### ISSUE TITLE
modem.lua:47: index expected, got string

### ISSUE THREAD

**Issue by lifewcody** [InZernetTechnologies/IPv2#8]
Line 47: `}`
Code block:
```
if _G.modems[rs.getSides()[a]] == nil then
    _G.modems[rs.getSides()[a]] = {
        ["TX"] = 0,
        ["RX"] = 0,
    }
end
```

I think this has to do with loading the modem cache back into the system.

Steps to reproduce:
1) Start core_router.lua
2) Reboot CC computer
3) Start core_router.lua again

**Comment by codywtworld** [comment]
Asking the real professionals haha
http://www.computercraft.info/forums2/index.php?/topic/28527-disappearing-variable-in-tale/
